4 new meme
andreyMalec/Meme-Board pull request #4
Opened 2020-04-13 15:55 UTC by andreyMalec

2020-04-14 14:07 UTC, midery requested changes

2020-04-14 14:07 UTC, midery commented on app/src/main/java/com/proj/memeboard/model/memeRepo/MemeRepo.kt
> +class MemeRepo(token: String) {
Здесь немного перепутаны зависимости: memeRepo не должен быть зависим от токена, memeRepo вообще не должен знать о существовании токена. 

Советую реализовать структуру классов так: 
1. Создать класс TokenStorage, который будет сохранять токен пользователя в prefs или БД. 
2. Создавать один инстанс OkHttp на все приложение. К нему подключать AuthorizationInterceptor, которому в конструктор провайдить этот TokenStorage. 
3. AuthorizationInterceptor на каждый запрос будет добавлять authToken, если он есть в хранилище. 
4. В методе auth/login класть в этот storage токен, в методе auth/logout - очищать.

2020-04-14 14:07 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/home/BaseMemeViewModel.kt
> +    internal val dao = MemesDatabase.getInstance(app)!!.memesDataDao()
Кажется, что хранить базу данных на presentation-слое не очень верно - это все-таки платформенная зависимость, и лучше было бы спрятать ее за репозиторием.

2020-04-14 14:07 UTC, midery commented on app/src/main/java/com/proj/memeboard/model/memeRepo/MemeRepoProvider.kt
> +        return MemeRepo(token)
Хотя репозиторий и можно создавать каждый раз, но я бы отдал предпочтение lazy-инициализации: ретрофит работает на рефлексии, и каждый раз создавать memeApi - это затратная операция.

2020-04-14 14:07 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/newMeme/NewMemeViewModel.kt
> +    private val dao = MemesDatabase.getInstance(app)!!.memesDataDao()
Не хочешь попробовать инъекцию зависимостей с помощью Dagger2? Этот паттерн широко используется на практике, и в твоем случае может сильно сократить количество бойлерплейта на самих экранах при инициализации.

2020-04-14 18:00 UTC, andreyMalec commented on app/src/main/java/com/proj/memeboard/model/memeRepo/MemeRepo.kt
> +class MemeRepo(token: String) {
я уже не передаю токен в текущей версии, а передаю апи
```suggestion
class MemeRepo(private val api: MemeApi) {
```
и я перенес создание ретрофита в object

```
object RepoProvider {
    private var userStorage: UserStorage? = null

    val memeRepo by lazy { MemeRepo(retrofit.create(MemeApi::class.java)) }
    val authRepo by lazy { AuthRepo(retrofit.create(AuthApi::class.java)) }

    private val client = OkHttpClient.Builder().addInterceptor { chain ->
        val original = chain.request()
        val request = original.newBuilder().apply {
            userStorage?.let {
                header("Authorization", it.getToken())
            }
            method(original.method, original.body)
        }.build()
        chain.proceed(request)
    }.build()

    private val retrofit = Retrofit.Builder().apply {
        baseUrl("https://demo2407529.mockable.io/")
        addConverterFactory(GsonConverterFactory.create())
        client(client)
    }.build()

    fun initUserStorage(fromContext: Context) {
        userStorage = UserStorageProvider.create(fromContext)
    }
}
```
в LoginViewModel я вызываю initUserStorage и потом везде дальше мы имеем токен из SharedPreferences

2020-04-14 18:19 UTC, andreyMalec commented on app/src/main/java/com/proj/memeboard/ui/main/home/BaseMemeViewModel.kt
> +    internal val dao = MemesDatabase.getInstance(app)!!.memesDataDao()
я мог бы добавить в существующий RepoProvider создание базы вместе с получением токена
```
    fun initUserStorage(fromContext: Context) {
        userStorage = UserStorageProvider.create(fromContext)
        initDao(fromContext)
    }
    
    private fun initDao(fromContext: Context) {
        dao = MemesDatabase.getInstance(fromContext)?.memesDataDao()
    }
```
и тогда передавать его в репозиторий
```
class MemeRepo(private val api: MemeApi, private val dao: MemesDao) {
```

2020-04-14 18:32 UTC, andreyMalec commented on app/src/main/java/com/proj/memeboard/ui/main/home/BaseMemeViewModel.kt
> +    internal val dao = MemesDatabase.getInstance(app)!!.memesDataDao()
но лучше сделать новый, чтобы не тянуть в этот работу с LiveData

2020-04-14 18:45 UTC, andreyMalec commented on app/src/main/java/com/proj/memeboard/ui/main/newMeme/NewMemeViewModel.kt
> +    private val dao = MemesDatabase.getInstance(app)!!.memesDataDao()
я планировал это начать, когда закончу со всеми заданиями

2020-04-15 09:11 UTC, midery commented on app/src/main/java/com/proj/memeboard/model/memeRepo/MemeRepo.kt
> +class MemeRepo(token: String) {
Хорошее решение, только я бы на твоем месте немного его доработал:
1. Лучше инициализировать storage не на логине, а в классе Application: иерархия экранов может поменяться, и storage останется неинициализированным
2. Возможно, стоит немного разделить предоставление зависимостей: один класс, который отвечает за зависимости сети (NetworkProvider), а другой, например, за репозитории. 
3. userStorage не обязательно быть nullable, может задействовать модификатор lateinit

2020-04-15 09:14 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/home/BaseMemeViewModel.kt
> +    internal val dao = MemesDatabase.getInstance(app)!!.memesDataDao()
Вполне хорошее решение, какой-нибудь MemesDBProvider вполне подойдет. И инициализировать его тоже лучше в классе App

2020-04-15 09:16 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/newMeme/NewMemeViewModel.kt
> +    private val dao = MemesDatabase.getInstance(app)!!.memesDataDao()
Мне кажется, тебе проще будет вначале заложить устойчивую конфигурацию, и потом на нее наращивать функционал, чем заниматься постоянным рефакторингом. Возможно, предоставление зависимостей через даггер будет выглядеть даже проще, чем сейчас, с object'ами. 
Но тут уже на твое усмотрение)

2020-04-15 09:19 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/home/BaseMemeViewModel.kt
> +    internal val dao = MemesDatabase.getInstance(app)!!.memesDataDao()
Кстати, по поводу LiveDat'ы: не хочешь попробовать поработать через RxJava / Coroutines Flow? 
Обычно на реальных проектах на слое interactor/repository используются именно они. 
Rx вполне можно считать многоплатформенной библиотекой, а корутины вообще инструментом языка. Таким образом, вообще не нужно будет тащить android-зависимости в интерфейс репозитория.

2020-04-16 14:03 UTC, merged