5 final again
andreyMalec/Meme-Board pull request #6
Opened 2020-04-22 16:31 UTC by andreyMalec

2020-04-23 18:11 UTC, midery requested changes

2020-04-23 18:11 UTC, midery commented on app/src/main/java/com/proj/memeboard/di/module/DbModule.kt
>          if (this::database.isInitialized.not()) {
Что-то очень странный вышел вызов инициализации базы. Зачем нам synchronized, хранение данных в классе, если базу мы по факту нигде при инжекте не используем? 
В модулях даггера вообще не должны храниться данные, они должны просто поставлять зависимости, и ничего больше. 

Если у тебя из этого модуля используется только memesDao, то лучше было бы запровайдить базу через контекст, а уже memesDao провадить через базу.

2020-04-23 18:11 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/Screens.kt
> +        private var fragment: Fragment? = null
Так лучше не делать, этот код потенциально может привести к memory leaks. 
функция getFragment() обычно именно создает фрагмент, она не может использоваться для его извлечения.

Для того, чтобы понять, выбран ли текущий таб, нужно использовать функцию Screen.getScreenKey(), которая служит как раз для идентификации экрана.

2020-04-23 18:11 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/login/LoginActivity.kt
> +        navHolder.setNavigator(SupportAppNavigator(this, -1))
Лучше инициализировать навигатор один раз при создании экрана, иначе здесь мы постоянно создаем новые и новые навигаторы

2020-04-23 18:11 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/MainActivity.kt
> +    private var pressAgain = true
Тут что-то с кодстайлом случилось) Не нужно так спешить)

Логика с закрытием экрана по нажатию на backPress по-хорошему должна быть во ViewModel, советую перенести туда.

2020-04-23 18:11 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/navigation/BottomNavigator.kt
> +        fragments.forEach {
Тут нужно причесать логику, хотя бы избавиться от дублирования кода.

2020-04-23 18:22 UTC, andreyMalec commented on app/src/main/java/com/proj/memeboard/ui/Screens.kt
> +        private var fragment: Fragment? = null
я это сделал, чтобы фрагменты не пересоздавались при переключениях

2020-04-24 14:11 UTC, midery requested changes

2020-04-24 14:11 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/Screens.kt
> +            return MemeDetailActivity.getExtraIntent(context, meme)
В идеале, формирование интента и парсинг интента должны быть описаны в screen-классе, потому что его ответственность - передача данных с экрана на экран. 
Так что советую сделать этому экрану компаньон с двумя утилитарными функциями.

2020-04-24 14:11 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/Screens.kt
> +        private var fragment: Fragment? = null
Тебе и не нужно будет их пересоздавать, если ты будешь пользоваться тегом screenKey.

Когда ты добавляешь фрагмент в fragmentManager, можно делать это так: 
```
fragmentTransaction.add(containerId, screen.getFragment(), screen.getScreenKey())
```
Таким образом, фрагмент добавится на экран и добавится в fragmentManager с тегом screenKey. 
После этого, ты сможешь использовать fragmentManager.findFragmentByTag(screen.getScreenKey()) для получения этого фрагмента, и переключения. 
Так что тебе необязательно хранить в screen'ах фрагменты, а в навигаторе список фрагментов: достаточно лишь хранить список ключей, и ключ от текущего видимого.

2020-04-24 14:11 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/detail/MemeDetailActivity.kt
> +        initTransitionListener()
По-моему, здесь не используется transitionListener, а просто изменяется радиус)

2020-04-24 17:03 UTC, midery commented
В данный момент, невозможно создать мем, из-за того что в туллбаре вместо кнопки create, кнопка с лупой из поиска мемов.

2020-04-24 17:19 UTC, midery commented
Небольшие придирки, которые фиксить необязательно, но просто чтобы приложение вело себя лучше, можно сделать:
1. Сейчас нельзя вернуться по клавише back к вкладке home/profile, если зайти на экран создания мема. Обычно этот функционал в приложениях присутствует.
2. Шаред транзишн в первый раз отрабатывает довольно скомканно: он начинает происходит, но изображение появляется уже после того, как новый экран становится видно, и это приводит к нестандартному поведению верстки.

2020-04-24 17:19 UTC, midery requested changes

2020-04-24 17:19 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/navigation/DetailNavigator.kt
> +    override fun activityForward(command: Forward) {
Для снабжения activity options'ами в навигаторе не нужно переопределять метод activityForward, там есть метод createStartActivityOptions, который можно задействовать, чтобы упростить этот механизм.

2020-04-24 17:19 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/home/MemeFragment.kt
> +            val navigator = DetailNavigator(it, options.toBundle())
Это неверно. Навигатор не должен создаваться каждый раз при нажатии на кнопку. Для передачи опций лучше завести отдельное поле в screen, и класть его в этот screen. В свою очередь, в методе createStartActivityOptions нужно извлечь screen из команды, проверить его тип, и извлечь опции.

2020-04-24 17:19 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/detail/MemeDetailActivity.kt
> +                viewModel.deleteMeme()
Получается, при удалении мема карточка не изменит своих размеров?

2020-04-24 17:19 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/detail/MemeDetailActivity.kt
> +                binding.card.radius = 21f
Не советую задавать радиус не через дименшны. На 1280х720 экране 8dp=16f, на 2560х1440 8dp=27f. 
Так что лучше завести под это дело константы, хранить их в dimens, и вытаскивать через context.resources.

2020-04-24 17:19 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/home/MemeAdapter.kt
> +                    val p1 = Pair(binding.card as View, "card")
Может быть, придумаем более говорящее название? Вроде sharedCardPair.

2020-04-27 09:34 UTC, midery requested changes

2020-04-27 09:34 UTC, midery commented on app/src/main/java/com/proj/memeboard/service/localDb/MemesDatabase.kt
> +            if (this::database.isInitialized.not()) {
Все еще вопрос: зачем здесь такая сложная логика? 
У даггера все модули по-дефолту lazy, и провайдят сущность один раз в один скоуп. Раз у тебя provides-метод помечен аннотацией singletone - он будет вызван только один раз. 
И поэтому мне не очень понятно, зачем хранить инстанс базы в самой себе, и зачем нам здесь доп. многопоточная синхронизация.

2020-04-27 09:34 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/navigation/BottomNavigator.kt
> +        if (::currentScreen.isInitialized && screenKey == currentScreen) return
Чтобы уйти от такой проверки, вполне можно проинициализировать currentScreen значением по-умолчанию (пустая строка). 
Вообще, lateinit проперти это хорошая штука, но не советую ими везде злоупотреблять. Если где-то появляется рефлексия и проверка на isInitialized - это верный признак того, что нужно делать проперти либо nullable, либо задавать дефолтное значение

2020-04-27 09:34 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/navigation/BottomNavigator.kt
> +    override fun createStartActivityOptions(command: Command, activityIntent: Intent): Bundle? {
Круто, что получилось совместить два навигатора в один, молодец!

2020-04-27 09:34 UTC, midery commented on app/src/main/res/values/dimen.xml
> +    <dimen name="dp8">8dp</dimen>
Лучше называть дименшны исходя из контекста, а то эта запись вообще ничего о нем не говорит. Например, home_card_raduis.

2020-04-27 09:34 UTC, midery commented on app/src/main/java/com/proj/memeboard/ui/main/MainActivity.kt
> +        if (pressAgain) {
Этот метод все еще лучше перенести в ViewModel: 
Он не отвечает за отображение контента, а скорее содержит в себе ui-логику: 
`если мы нажали на бек один раз - покажи сообщение, если нажали второй раз, и таймер не истек - выйди из приложения.` 
Это целиком и полностью ответственность VM, а не passive view, поэтому советую перенести код туда.

2020-04-27 10:05 UTC, midery approved these changes

2020-04-27 10:06 UTC, merged